name = "authfordev-user"
main = "app/worker.ts"
compatibility_date = "2023-09-04"

[vars]
API_URL_MAILCHANNELS = "https://api.mailchannels.net/tx/v1"

[[durable_objects.bindings]]
name = "DO_USER"
class_name = "DurableObjectUser"

[[durable_objects.bindings]]
name = "DO_CHALLENGE"
class_name = "DurableObjectChallenge"

[[durable_objects.bindings]]
name = "DO_PASSKEY"
class_name = "DurableObjectPasskey"

[[migrations]]
tag = "v1"
new_classes = [
    "DurableObjectUser",
    "DurableObjectChallenge",
    "DurableObjectPasskey",
]
